logger/callsigns/views.py
import datetime
from flask import (Blueprint, abort, flash, make_response, redirect,
                   render_template, request, url_for)
from flask_login import current_user, login_required

from sqlalchemy import desc, func, and_

from logger.forms import CallsignForm
from logger.helpers import adiftext
from logger.models import QSO, Callsign, User, db

callsigns = Blueprint('callsigns', __name__, template_folder='templates')

ROWS_PER_PAGE = 10

@callsigns.route("/")
@login_required
def index():
    '''Callsign index. show who has what callsign'''
    callsignlist = db.session.query(User.name, Callsign.name, func.count(QSO.id)).join(Callsign, QSO.station_callsign == Callsign.name).join(User, Callsign.user_id == User.id).group_by(User.name, Callsign.name).order_by(func.count(QSO.id).desc()).all()
    return render_template('callsignindex.html', callsigns=callsignlist)

@callsigns.route("/<callsign>/qsos")
@login_required
def call(callsign):
    '''Homepage for a callsign. We should show a table of all the QSOs logged against
    this callsign.'''
    #swap _ for /
    callsign = callsign.replace('_', '/')
    callsignid = Callsign.query.filter_by(name=callsign).first().id
    allqsos = QSO.query.filter_by(station_callsign = callsign).order_by(QSO.qso_date.desc(), QSO.time_on.desc()).all()
    return render_template('callsign.html', qsos=allqsos, station_callsign=callsign, callsignid=callsignid)


@callsigns.route("/create", methods=['GET','POST'])
@login_required
def callsigncreate():
    '''Create a Callsign'''
    form = CallsignForm()
    if request.method == 'POST':
        name = request.form.get('name','').upper() or None
        newcallsign = Callsign(name=name, user_id=current_user.get_id())
        db.session.add(newcallsign)
        db.session.commit()
        return redirect(url_for('users.profile', user=current_user.name))
    return render_template('callsigncreateform.html', form=form, username=current_user.name)


@callsigns.route("/delete/<int:id>")
@login_required
def callsigndelete(id):
    callsign = Callsign.query.filter_by(id=id).first()
    if int(callsign.user_id) == int(current_user.get_id()):
        callsign1 = callsign.query.get_or_404(id)
        db.session.delete(callsign1)
        db.session.commit()
        return redirect(url_for('users.profile', user=current_user.name))
    else:
        abort(403)


@callsigns.route("/export/<int:id>")
@login_required
def callsignexport(id):
    '''Export all QSOs associated with a callsign'''
    callsign = Callsign.query.filter_by(id=id).first()
    if int(callsign.user_id) == int(current_user.get_id()):
        qsos = QSO.query.filter_by(station_callsign=callsign.name).all()
        response = make_response(adiftext(qsos), 200)
        response.mimetype = "text/plain"
        cdtext = 'attachment; filename=' + callsign.name + '.adi'
        response.headers = {'Content-disposition': cdtext}
        return response
    else:
        abort(403)

@callsigns.route("/<call>/virtual")
@login_required
def virtual(call):
    '''list all qsos where the callsign appears as the <call> not the station_callsign'''
    call = call.replace('_', '/')
    calls = Callsign.query.filter_by(user_id=current_user.get_id()).all()
    callsigns = []
    for vircall in calls:
        callsigns.append(str(vircall))
    virtualcall = QSO.query.filter_by(call = call).order_by(QSO.qso_date.desc(), QSO.time_on.desc()).all()
    callsign = Callsign.query.filter_by(name=call).first()
    matches = {}
    for vcall in virtualcall:
        matches[vcall.id] = QSO.query.with_entities(QSO.id, QSO.station_callsign, QSO.call, QSO.band, QSO.mode, QSO.qso_date, QSO.time_on).filter(and_(func.date(QSO.qso_date) >= '2023-07-01'),(func.date(QSO.qso_date) <= '2023-08-31'), QSO.call == vcall.station_callsign, QSO.station_callsign == vcall.call, QSO.band == vcall.band, QSO.mode == vcall.mode, QSO.qso_date == vcall.qso_date).all()
    print(matches)
    print(call)
    return render_template('virtualcallsign.html', call=call, qsos=virtualcall, callsign=callsign, matches=matches)

@callsigns.route("/<call>/clubcalls")
@login_required
def operator(call):
    '''list all qsos where the callsign appears as the <operator> not the station_callsign'''
    call = call.replace('_', '/')
    calls = Callsign.query.filter_by(user_id=current_user.get_id()).all()
    callsigns = []
    for vircall in calls:
        callsigns.append(str(vircall))
    opcalls = QSO.query.filter(QSO.operator == call, QSO.station_callsign != call).order_by(QSO.qso_date.desc(), QSO.time_on.desc()).all()
    callsign = Callsign.query.filter_by(name=call).first()
    return render_template('virtualcallsign.html', call=call, qsos=opcalls, callsign=callsign)


@callsigns.route("/<call>/search")
@login_required
def search(call):
    call = call.replace('_', '/')
    calls = Callsign.query.filter_by(user_id=current_user.get_id()).all()
    callsigns = []
    for mycall in calls:
        callsigns.append(str(mycall))
    qsos = QSO.query.filter(QSO.station_callsign.in_(callsigns), QSO.call == call).all()
    return render_template('callsignsearch.html', call=call, qsos=qsos, callsigns=callsigns)


@callsigns.route("/<callsign>/duplicates")
def dupes(callsign):
    '''find duplicates within a callsign based on call, band, mode, date and time'''
    callsign = callsign.replace('_', '/')
    qsos = QSO.query.filter_by(station_callsign = callsign).all()
    possdupes = []
    for leftqso in qsos:
        for rightqso in qsos:
            score = 0
            flag = False
            for dupe in possdupes:
                if (dupe[1] == leftqso) and (dupe[0] == rightqso):
                    flag = True
                    continue
            if flag == True:
                continue
            if leftqso.id == rightqso.id:
                continue
            if leftqso.call != rightqso.call:
                continue
            if leftqso.band == rightqso.band:
                score += 1
            if leftqso.mode == rightqso.mode:
                score += 1
            if leftqso.submode == rightqso.submode:
                score += 1
            if leftqso.mode == rightqso.submode:
                score += 1
            if leftqso.submode == rightqso.mode:
                score += 1
            leftt = datetime.datetime.combine(leftqso.qso_date, leftqso.time_on)
            rightt = datetime.datetime.combine(rightqso.qso_date, rightqso.time_on)
            deltat = leftt - rightt
            if (deltat >= datetime.timedelta(0) and (deltat <= datetime.timedelta(0.5))): # QSOs are within half of a day of each other
                possdupes.append((leftqso, rightqso, score, deltat))
    if len(possdupes) > 1:
        possdupes =sorted(possdupes, key=lambda x: x[2], reverse=True)
    return render_template('dups.html', possdupes=possdupes, callsign=callsign)

logger/events/views.py
import datetime

from flask import (Blueprint, abort, flash, make_response, redirect,
                   render_template, request, url_for, session)
from flask_login import current_user, login_required

from logger.forms import EventForm, SelectedEventForm
from logger.helpers import adiftext
from logger.models import QSO, Callsign, Event, User, db

events = Blueprint('events', __name__, template_folder='templates')

ROWS_PER_PAGE = 10
EXPORT_DATES = ['qso_date', 'qso_date_off', 'qslrdate', 'qslsdate', 'lotw_qslsdate', 'lotw_qslrdate', 'eqsl_qslsdate', 'eqsl_qslrdate',
                'qrzcom_qso_upload_date']
EXPORT_TIMES = ['time_on', 'time_off']

@events.route("/<username>")
@login_required
def eventlist(username):
    '''Homepage for a users events. We should show a table of all the events logged against
    this user.'''
    if username == current_user.name:
        page = request.args.get('page', 1, type=int)
        todays_date = datetime.datetime.now()
        future = Event.query.filter(Event.user_id==current_user.get_id(), 
                                    Event.start_date >= todays_date).order_by(Event.start_date.desc()).all()
        current = Event.query.filter(Event.user_id==current_user.get_id(), 
                                     Event.start_date <= todays_date, Event.end_date >= todays_date).order_by(Event.start_date.desc()).all()
        past = Event.query.filter(Event.user_id==current_user.get_id(), 
                                  Event.end_date <= todays_date).order_by(Event.start_date.desc()).all()
        print (future, current, past)
        eventpage = Event.query.filter_by(user_id=current_user.get_id()).order_by(Event.start_date.desc()).paginate(page=page, per_page=ROWS_PER_PAGE)
        allevents = Event.query.filter_by(user_id=current_user.get_id()).all()
        return render_template('eventlist.html', eventpage=eventpage, allevents=allevents, username=username, future=future, current=current, past=past)
    else:
        abort(403)

@events.route("/view/<int:id>")
@login_required
def eventview(id):
    '''View an event and the QSOs associated with it'''
    event = Event.query.filter_by(id=id).first()
    eventtypes = ['SOTA', 'POTA', 'SOTA-POTA']
    if int(event.owner.id) == int(current_user.get_id()):
        return render_template('eventview.html', event=event, eventtypes=eventtypes)
    else:
        abort(403)

@events.route("/export/<int:id>")
@login_required
def export(id):
    '''Export all QSOs associated with an event'''
    event = Event.query.filter_by(id=id).first()
    if int(event.owner.id) == int(current_user.get_id()):
        qsos = QSO.query.filter(QSO.events.any(id=id)).all()
        response = make_response(adiftext(qsos), 200)
        response.mimetype = "text/plain"
        exportevent = Event.query.filter_by(id=id).first()
        cdtext = 'attachment; filename=' + exportevent.name + '.adi'
        response.headers = {'Content-disposition': cdtext}
        return response
    else:
        abort(403)


def save_changes(event, form, new):
        start_date = datetime.datetime.strptime(request.form['start_date'], '%Y-%m-%d').date()
        start_time = datetime.datetime.strptime(request.form['start_time'], '%H:%M').time()
        event.start_date = datetime.datetime.combine(start_date, start_time)
        print(event.start_date)
        end_date = datetime.datetime.strptime(request.form['end_date'], '%Y-%m-%d').date()
        end_time = datetime.datetime.strptime(request.form['end_time'], '%H:%M').time()
        event.end_date = datetime.datetime.combine(end_date, end_time)
        event.name = request.form['name']
        event.type = request.form['type']
        event.sota_ref = request.form.get('sota_ref', '') or None
        event.pota_ref = request.form.get('pota_ref', '') or None
        event.sat_name = request.form.get('sat_name', '') or None
        event.sat_mode = request.form.get('sat_mode', '') or None
        event.my_gridsquare = request.form.get('my_gridsquare', '') or None
        event.comment = request.form['comment']
        event.clubcall = request.form.get('clubcall', '') or None
        event.user_id=current_user.get_id()
        if new:
            db.session.add(event)
        db.session.commit()


@events.route("/create", methods=['GET','POST'])
@login_required
def eventcreate():
    '''Create an Event'''
    form = EventForm()
    if request.method == 'POST':
        event = Event()
        save_changes(event, form, new=True)
        flash('Event created successfully!')
        return redirect(url_for('events.eventlist', username=current_user.name))
    return render_template('eventcreateform.html', form=form, username=current_user.name)


@events.route("/delete/<int:id>")
@login_required
def eventdelete(id):
    event = Event.query.filter_by(id=id).first()
    if event.user_id == int(current_user.get_id()):
        event.selected_by[:] = []
        event.qsos[:] = []
        event.configs[:] = []
        db.session.commit()
        db.session.delete(event)
        db.session.commit()
        message = '"' + event.name + '" successfully deleted'
        flash(message, 'info')
        return redirect(request.referrer)
    else:
        abort(403)


@events.route("/edit/<int:id>", methods=['GET', 'POST'])
@login_required
def eventedit(id):
    event = Event.query.filter_by(id=id).first()
    if int(event.user_id) == int(current_user.get_id()):
        event1 = event.query.get_or_404(id)
        if event1:
            form = EventForm(formdata=request.form, obj=event1)
            if request.method == 'POST' and form.validate():
                save_changes(event1, form, new=False)
                flash('Event updated successfully!')
                return redirect(url_for('events.eventlist', username=current_user.name))
            return render_template('eventcreateform.html', form=form, username=current_user.name)
        else:
            return 'Error loading event #{id}'.format(id=id)


@events.errorhandler(403)
def page_not_found(e):
    # note that we set the 403 status explicitly
    return render_template('403.html'), 403


@events.route("/select/<username>", methods=['GET', 'POST'])
@login_required
def selectevents(username):
    form = SelectedEventForm()
    if request.method == 'POST' and form.validate():
        user = User.query.filter_by(name=username).first()
        print (request.form.getlist('Search'))
        user.selected_events[:] = Event.query.filter(Event.id.in_(request.form.getlist('Search')))
        db.session.commit()
        flash('Selected Events updated', 'info')
        return redirect(session['back'])
    allevents = Event.query.filter_by(user_id=current_user.get_id()).all()
    session['back'] = request.referrer
    print(session['back'])
    alleventsjson = []
    for e in allevents:
        alleventsjson.append({'val': e.name, 'id' : e.id})
    page = request.args.get('page', 1, type=int)
    eventpage = Event.query.filter_by(user_id=current_user.get_id()).order_by(Event.start_date.desc()).paginate(page=page, per_page=ROWS_PER_PAGE)
    user = User.query.filter_by(name=username).first()
    selectedevents=[]
    for event in user.selected_events:
        selectedevents.append(event.id)    
    print (selectedevents)
    # seleventsjson = []
    # for e in selectedevents:
    #     seleventsjson.append(Event.query.filter_by(id=e.event).first().id)
    return render_template('selectedeventsform.html', username=current_user.name, eventpage=eventpage, selectedevents=selectedevents,
                           allevents=allevents, alleventsjson=alleventsjson, form=form, seleventsjson=selectedevents)

logger/templates/configlist.html
{% extends 'base.html' %}
{% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
{% endblock %}
{% block hero %}is-warning{% endblock %}
{% block herobody %}
                <h1 class="title is-size-1">
                    {% block title %} Station Configurations for {{ username }} {% endblock %}
                </h1>
                <div class="subtitle is-4 algolia-lvl1">
                    <p>{% if allconfigs|length == 1 %} There is 1 station configuration for this user.{% else %}There are {{ allconfigs| length }} station configurations for this user{% endif %}</p>     
                </div>
{% endblock%}
{% block content %}
    <div class="container">
        <div class="box">
            <h1 class="title">Station Configurations</h1>
            {% if configpage.items %}
            <table class="table is-striped is-hoverable">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Edit</th>
                        <th>Name</th>
                        <th>Rig</th>
                        <th>Antenna</th>
                        <th>Used in QSOs</th>
                        <th>Used in Events</th>
                        <th>Comment</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for config in configpage.items %}
                    <tr>
                        <td>{{ config.id }}</td>
                        <td><a class="button is-link is-small" href="{{ url_for ('configurations.configedit', id=config.id) }}"><span class="icon is-small"><i class="fa-solid fa-pen-to-square"></i></span><span>Edit</span></a></td>
                        <td><a href="{{ url_for ('configurations.configview', id=config.id) }}" title="{{ config.name }}">{{ config.name }}</a></td>
                        <td>{{ config.rig.name }}</td>
                        <td>{{ config.antenna.name }}</td>
                        <td>{% if config.qsos %}{{ config.qsos|length }}{% endif %}</td>
                        <td>{% if config.events %}{{ config.events|length }}{% endif %}</td>
                        <td>{{ config.comment }}</td>
                        <td><a class="button is-danger is-small" href="{{ url_for ('configurations.configdelete', id=config.id) }}" onclick="return confirm('Are you sure you want to delete this entry?')">Delete</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p class="subtitle">No Station Configurations defined yet</p>
            {% endif %}
            <nav class="pagination" role="navigation" aria-label="pagination">
                <a class="pagination-previous" {% if configpage.has_prev %}href="{{ url_for('configurations.configlist', username=current_user.name, page=configlist.prev_num) }}"{% else %}disabled {% endif %} title="This is the first page">Previous</a>
                <a class="pagination-next" {% if configpage.has_next %}href="{{ url_for('configurations.configlist', username=current_user.name, page=configlist.next_num) }}"{% else %}disabled {% endif %}>Next page</a>
                <ul class="pagination-list">
                    {% for page_num in configpage.iter_pages() %}
                        {% if page_num %}
                            {% if page_num != configpage.page %}
                            <li>
                                <a class="pagination-link" href="{{ url_for('configurations.configlist', username=current_user.name, page=page_num) }}" aria-label="Goto page {{ page_num }}">{{ page_num }}</a>
                            </li>
                            {% else %}
                            <li>
                                <a class="pagination-link is-current" href="{{ url_for('configurations.configlist', username=current_user.name, page=page_num) }}" aria-label="Page {{ page_num }}" aria-current="page">{{ page_num }}</a>
                            </li>
                            {% endif %}
                        {% else %}
                            <li>
                                <span class="pagination-ellipsis">&hellip;</span>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </nav>
        </div>
        <div class="box">
            <div class="level">
                <div class="level-left">
                    <p class="level-item">Click to add a new Station Configuration</p>
                    <a class="button is-link level-item" href="{{ url_for('configurations.configcreate') }}">Add Station Configuration</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

logger/templates/profile.html
{% extends "base.html" %}
{% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', () => {
        // Functions to open and close a modal
        function openModal($el) {
        $el.classList.add('is-active');
        }
    
        function closeModal($el) {
        $el.classList.remove('is-active');
        }
    
        function closeAllModals() {
        (document.querySelectorAll('.modal') || []).forEach(($modal) => {
            closeModal($modal);
        });
        }
    
        // Add a click event on buttons to open a specific modal
        (document.querySelectorAll('.js-modal-trigger') || []).forEach(($trigger) => {
        const modal = $trigger.dataset.target;
        const $target = document.getElementById(modal);
    
        $trigger.addEventListener('click', () => {
            openModal($target);
        });
        });
    
        // Add a click event on various child elements to close the parent modal
        (document.querySelectorAll('.modal-background, .modal-close, .modal-card-head .delete, .modal-card-foot .button.cancel') || []).forEach(($close) => {
        const $target = $close.closest('.modal');
    
        $close.addEventListener('click', () => {
            closeModal($target);
        });
        });

        // Add a keyboard event to close all modals
        document.addEventListener('keydown', (event) => {
        const e = event || window.event;
    
        if (e.keyCode === 27) { // Escape key
            closeAllModals();
        }
        });
    });
</script>  
{% endblock %}
{% block herobody %}
			<h1 class="title algolia-lvl0">
				{% block title %} <p>Welcome, {{ current_user.name }}</p> {% endblock %}
			</h1>
			{% if (callsigns is defined) and callsigns %}
			<div class="subtitle is-4 algolia-lvl1">
				<p>You have the following callsigns</p>     
			</div>
			{% endif %}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="box">
            <h1 class="title"><a href="{{ url_for('events.eventlist', username=current_user.name) }}">Selected Events</a></h1>
            <nav class="level">
                <div class="level-left">
                    <div class="level-item">
                        {% for event in current_user.selected_events %}
                        <div class="level-item">
                            <div class="control">
                                <div class="tags has-addons">
                                    <a class="tag is-primary" href="{{ url_for ('events.eventview', id=event.id) }}" >{{ event.name }}</a>
                                    <span class="tag is-info is-light">{{ event.type }}</span>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="level-right">
                    <div class="level-item">
                        <a class="button is-link" href="{{ url_for('events.selectevents', username=current_user.name) }}">Change Selected</a>
                    </div>
                </div>
            </nav>
        </div>
        <div class="box">
            <h1 class="title">Callsigns</h1>
            {% if current_user.callsigns %}
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Callsign</th>
                        <th>DXCC</th>
                        <th>QSOs</th>
                        <th>Last QSO</th>
                        <th>Add QSO</th>
                        <th>Export</th>
                        <th>Del Callsign</th>
                        <th>Check Duplicates</th>
                    </tr>
                </thead>
                <tbody>
                {% for callsign in current_user.callsigns %}
                    <tr>
                        <td>{{ callsign.id }}</td>
                        <td><a class="has-text-weight-semibold" href="{{ url_for ('callsigns.call', callsign=callsign['name'] | replace('/','_'))  }}">{{ callsign.name }}</a></td>
                        <td>{{ countrylookup(callsign.name) }}</td>
                        <td>{{ qsocount(callsign.name) }}</td>
                        <td>{% if latestqso(callsign.name) != 'N/A' %}{{ latestqso(callsign.name) }}{% endif %}</td>
                        <td><a class="button is-link is-small" href="{{ url_for('qsos.postnewqso', station_callsign=callsign.name | replace('/','_')) }}">Add QSO</a></td>
                        <td><a class="has-text-primary-dark" href="{{ url_for ('callsigns.callsignexport', id=callsign.id | replace('/','_'))  }}"><span class="icon"><i class="fa-solid fa-file-arrow-down"></i></span>Export</a></td>
                        <td><a class="has-text-danger is-small" href="{{ url_for('callsigns.callsigndelete', id=callsign.id) }}" onclick="return confirm('Are you sure you want to delete this entry?')">Delete</a></td>
                        <td><a class="has-text-info" href="{{ url_for('callsigns.dupes', callsign=callsign.name | replace('/','_')) }}">Check Duplicates</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p class="subtitle">You have no callsigns defined.</p>
            {% endif %}
        </div>
        {% if virtualcall %}
        <div class="box">
            <h1 class="title">Virtual Logbooks</h1>
            <p class="submit">QSOs on the system where you appear as the Called party.</p>
            <table class="table">
                <thead>
                    <tr>
                        <th>Callsign</th>
                        <th>DXCC</th>
                        <th>QSOs</th>
                    </tr>
                </thead>
                <tbody> 
                {% for callsign, calls in virtualcall|groupby('call') %}
                    <tr>
                        <td><a href="{{ url_for('callsigns.virtual', call=callsign | replace('/','_') ) }}">{{ callsign }}</a></td>
                        <td>{{ countrylookup(callsign) }}</td>
                        <td>{{ calls|length }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
        {% if operatorcall %}
        <div class="box">
            <h1 class="title">Club Callsigns Operated</h1>
            <p class="submit">QSOs on the system where you appear as the Operator of another Callsign.</p>
            <table class="table">
                <thead>
                    <tr>
                        <th>Callsign</th>
                        <th>DXCC</th>
                        <th>QSOs</th>
                    </tr>
                </thead>
                <tbody> 
                {% for callsign, calls in operatorcall|groupby('operator') %}
                    <tr>
                        <td><a href="{{ url_for('callsigns.operator', call=callsign | replace('/','_') ) }}">{{ callsign }}</a></td>
                        <td>{{ countrylookup(callsign) }}</td>
                        <td>{{ calls|length }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
        <div class="box">
            <div class="level">
                <div class="level-left">
                    <p class="level-item">Add a new callsign</p>
                    <a type="button" class="js-modal-trigger button is-link" data-target="modal-add-callsign"">Add a callsign</a>
                </div>
                <div class="level-right">
                    <p class="level-item">Import QSOs from ADIF and apply Selected Events.</p>
                    <a class="button is-link level-item" href="{{ url_for('qsos.uploadqsos', user=current_user.name )}} ">Select ADI File</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block bottombody %}
<div id="modal-add-callsign" class="modal">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Add Callsign</p>
            <button class="delete" aria-label="close"></button>
        </header>
        <section class="modal-card-body">
            <form method="POST" id="callsignform">
                {{ form.csrf_token }}
                <div class="field">
                    {{ form.name.label(class_='label') }}
                    <div class="control">
                        {{ form.name(class_="input rig") }}
                    </div>
                    <p class="help">Callsign [eg M7ETU]</p>
                </div>
                {% if form.name.errors %}
                <ul class="errors">
                    {% for error in form.name.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <input type="hidden" name="formsubmitted" value="callsign">
            </form> 
        </section>
        <footer class="modal-card-foot">
            <button class="button is-success" name="add_callsign" type="submit" form="callsignform">Add Callsign</button>
            <button class="button cancel">Cancel</button>
        </footer>
    </div>
</div>
{% endblock %}

logger/templates/virtualcallsign.html
{% extends 'base.html' %}
{% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link href="https://cdn.datatables.net/v/bm/dt-1.13.4/cr-1.6.2/fc-4.2.2/fh-3.3.2/rg-1.3.1/sb-1.4.2/sp-2.1.2/sl-1.6.2/datatables.min.css" rel="stylesheet"/>
<script src="https://cdn.datatables.net/v/bm/dt-1.13.4/cr-1.6.2/fc-4.2.2/fh-3.3.2/rg-1.3.1/sb-1.4.2/sp-2.1.2/sl-1.6.2/datatables.min.js"></script>
{% endblock %}
{% block hero %}is-link{% endblock %}
{% block herobody %}
                <h1 class="title is-size-1">
                    {% block title %}Virtual QSOs for {{ call }} {% endblock %}
                </h1>
                <div class="subtitle is-4 algolia-lvl1">
                    <p>DXCC is {{ get_adif_id(call) }}: {{ countrylookup(call) }}, ITU Zone is {{ dxccituz(call) }}, CQ Zone is {{ dxcccqz(call) }}, {{ qsos|length }} QSOs for this callsign.</p>     
                </div>
{% endblock %}
{% block content %}
        <div class="container">
            <div class="box">
                <h1 class="title">Virtual QSOs</h1>
                <table id="virtual" class="table is-striped is-hoverable">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Time</th>
                            <th>Station Callsign</th>
                            <th>Call</th>
                            <th>Band</th>
                            <th>Mode</th>
                            <th>Gridsquare</th>
                            <th>My Gridsquare</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for qso in qsos %}
                        <tr>
                            <td>{{ qso.qso_date }}</td>
                            <td>{{ qso.time_on }}</td>
                            <td><a href="{{ url_for('callsigns.search', call=qso.station_callsign | replace('/','_') )}}">{{ qso.station_callsign }}</a></td>
                            <td>{{ qso.call }}</td>
                            <td data-order="{{ bandsortorder(qso.band) }}">{{ qso.band }}</td>
                            <td>{{ qso.mode }}</td>
                            <td>{{ qso.gridsquare }}</td>
                            <td>{{ qso.my_gridsquare }}</td>
                        {% else %}
                        No QSOs
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
{% endblock %}
{% block bottombody %}
<script>
$(document).ready(function () {
    $('#virtual').DataTable({
        lengthMenu: [
            [10, 25, 50, -1],
            [10, 25, 50, 'All'],
        ],
        order: [[0, 'desc'], [1, 'desc']],
        stateSave: true
    });
});
</script>
{% endblock %}